### ISSUE TITLE
Startup issue with docker compose

### ISSUE THREAD

**Issue by pierre-josselin** [FIWARE/trusted-issuers-list#8]
No problem with the example commands:

```
docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=user -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=db mysql
```

```
docker run --network host quay.io/fiware/trusted-issuers-list:0.0.1
```

But turned into docker compose:

```yaml
version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db

  trusted-issuers:
    image: quay.io/fiware/trusted-issuers-list:0.0.1
    network_mode: host

```

It produces the following errors and exit:

```
trusted-issuers-1  | 08:45:22.175 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
trusted-issuers-1  | com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  |      at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
trusted-issuers-1  |      at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
trusted-issuers-1  |      at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
trusted-issuers-1  |      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
trusted-issuers-1  |      at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
trusted-issuers-1  |      at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
trusted-issuers-1  |      at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
trusted-issuers-1  |      at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.build(Unknown Source)
trusted-issuers-1  |      at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
trusted-issuers-1  |      at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2737)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
trusted-issuers-1  |      at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
trusted-issuers-1  |      at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
trusted-issuers-1  |      at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
trusted-issuers-1  |      at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
trusted-issuers-1  |      at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
trusted-issuers-1  |      at org.fiware.iam.Application.main(Application.java:8)
trusted-issuers-1  | Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  |      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
trusted-issuers-1  |      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
trusted-issuers-1  |      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
trusted-issuers-1  |      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
trusted-issuers-1  |      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:581)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:536)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:423)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1427)
trusted-issuers-1  |      at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:944)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:814)
trusted-issuers-1  |      ... 31 common frames omitted
trusted-issuers-1  | Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
trusted-issuers-1  |      at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:575)
trusted-issuers-1  |      ... 37 common frames omitted
trusted-issuers-1  |
trusted-issuers-1  | 08:45:22.199 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
trusted-issuers-1  |
trusted-issuers-1  | Message: Failed to initialize pool: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  | Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration)
trusted-issuers-1  | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]
trusted-issuers-1  |
trusted-issuers-1  | Message: Failed to initialize pool: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  | Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921)
trusted-issuers-1  |      at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
trusted-issuers-1  |      at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
trusted-issuers-1  |      at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
trusted-issuers-1  |      at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
trusted-issuers-1  |      at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
trusted-issuers-1  |      at org.fiware.iam.Application.main(Application.java:8)
trusted-issuers-1  | Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]
trusted-issuers-1  |
trusted-issuers-1  | Message: Failed to initialize pool: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  | Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
trusted-issuers-1  |      at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2737)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
trusted-issuers-1  |      ... 9 common frames omitted
trusted-issuers-1  | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
trusted-issuers-1  |      at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
trusted-issuers-1  |      at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
trusted-issuers-1  |      at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
trusted-issuers-1  |      at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.build(Unknown Source)
trusted-issuers-1  |      at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
trusted-issuers-1  |      at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
trusted-issuers-1  |      ... 16 common frames omitted
trusted-issuers-1  | Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  |      at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
trusted-issuers-1  |      at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
trusted-issuers-1  |      at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
trusted-issuers-1  |      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
trusted-issuers-1  |      at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
trusted-issuers-1  |      ... 23 common frames omitted
trusted-issuers-1  | Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
trusted-issuers-1  |
trusted-issuers-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
trusted-issuers-1  |      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
trusted-issuers-1  |      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
trusted-issuers-1  |      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
trusted-issuers-1  |      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
trusted-issuers-1  |      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
trusted-issuers-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:581)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:536)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:423)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1427)
trusted-issuers-1  |      at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:944)
trusted-issuers-1  |      at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:814)
trusted-issuers-1  |      ... 31 common frames omitted
trusted-issuers-1  | Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
trusted-issuers-1  |      at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
trusted-issuers-1  |      at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:575)
trusted-issuers-1  |      ... 37 common frames omitted
trusted-issuers-1  |
trusted-issuers-1 exited with code 1
```

Is there any extra config required for use with docker compose?

**Comment by wistefan** [comment]
I'm not using docker-compose, but as far as I see you are running the mysql not in the host-network, thus ist won't be available in localhost:3306. Try to remove the ports and add the network_mode: host

**Comment by pierre-josselin** [comment]
Hi @wistefan,

Thank you for your reply. I initially tried this without network mode and it was already producing the same error. So I wanted to start from the working example in the readme.

After some tests, I confirm that the following script produce the same error:

```yaml
version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    network_mode: host

  trusted-issuers:
    image: quay.io/fiware/trusted-issuers-list:0.0.1
    network_mode: host
```

I also tried to set the env variables, without success:

```
DATASOURCES_DEFAULT_URL: "jdbc:mysql://mysql:3306/db"
DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
DATASOURCES_DEFAULT_USERNAME: "user"
DATASOURCES_DEFAULT_PASSWORD: "password"
DATASOURCES_DEFAULT_DIALECT: "MYSQL"
```

**Comment by pierre-josselin** [comment]
Here is my initial script:

```yaml
version: "3"
services:
  mysql-trusted-issuers-list:
    image: "mysql:8.1"
    hostname: "mysql-trusted-issuers-list"
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
    restart: "always"
    volumes:
      - "./data/mysql-trusted-issuers-list:/var/lib/mysql"

  trusted-issuers-list:
    image: "quay.io/fiware/trusted-issuers-list:0.1.0"
    hostname: "trusted-issuers-list"
    environment:
      DATASOURCES_DEFAULT_URL: "jdbc:mysql://mysql-trusted-issuers-list:3306/db"
      DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      DATASOURCES_DEFAULT_USERNAME: "user"
      DATASOURCES_DEFAULT_PASSWORD: "password"
      DATASOURCES_DEFAULT_DIALECT: "MYSQL"
    restart: "always"
    depends_on:
      - "mysql-trusted-issuers-list"

```

**Comment by wistefan** [comment]
When trying out locally, your script works well for me. This might be something with your local networking or docker installation.

**Comment by pierre-josselin** [comment]
Curious, I just created a new Debian 11 machine and installed [Docker Engine](https://docs.docker.com/engine/install/debian/) but still get the errors.

I will do some additional testing and keep you informed!

**Comment by pierre-josselin** [comment]
OK, I understand. At first startup, mysql takes some time before accepting connections. The trusted issuer list starts faster and cannot connect to mysql, it doesn't retry after X seconds and crashes directly.

Thank you for your help!
